# Generated by Django 4.0.3 on 2022-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='none', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='flat_no',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tower_no',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='none', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
