# Generated by Django 4.0.3 on 2022-04-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
