# Generated by Django 4.0.3 on 2022-04-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('suggestion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
